fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        lis:
            client: default
            types:
                user:
                    properties:
                        id:
                            type: integer
                        firstName:
                            type: string
                        lastName:
                            type: string
                        email:
                            type: string
                        deleted:
                            type: boolean
                        userType:
                            type: object
                            properties:
                                id:
                                    type: integer
                        position:
                            type: object
                            properties:
                                id:
                                    type: integer
                        team:
                            type: object
                            properties:
                                id:
                                    type: integer
                    persistence:
                        driver: orm
                        model: App\Entity\User
                        repository: App\Repository\UserRepository
                        finder: ~
                        provider: ~
                project:
                    properties:
                        id:
                           type: integer
                        name:
                           type: string
                        description:
                           type: string
                        startDate:
                           type: date
                        estimatedDuration:
                           type: date
                        deleted:
                           type: boolean
                        unixStartDate:
                           type: integer
                        unixEstimatedDuration:
                            type: integer
                        finished:
                           type: boolean
                        projectType:
                            type: object
                            properties:
                                id:
                                   type: integer
                        userCreated:
                            type: object
                            properties:
                                id:
                                   type: integer
                    persistence:
                        driver: orm
                        model: App\Entity\Project
                        repository: App\Repository\ProjectRepository
                        finder: ~
                        provider: ~
                participant:
                    properties:
                        id:
                            type: integer
                        project:
                            type: object
                            properties:
                                id:
                                   type: integer
                    persistence:
                        driver: orm
                        model: App\Entity\Participant
                        repository: App\Repository\ParticipantRepository
                        finder: ~
                        provider: ~
                bonus:
                    properties:
                        id:
                           type: integer
                        value:
                           type: integer
                        date:
                           type: date
                        unixDateCreated:
                           type: integer
                        unixDate:
                            type: integer
                        deleted:
                           type: boolean
                    persistence:
                        driver: orm
                        model: App\Entity\Bonus
                        repository: App\Repository\BonusRepository
                        finder: ~
                        provider: ~
                salary:
                    properties:
                        id:
                           type: integer
                        unixDateValid:
                           type: integer
                        deleted:
                           type: boolean
                    persistence:
                        driver: orm
                        model: App\Entity\Salary
                        repository: App\Repository\SalaryRepository
                        finder: ~
                        provider: ~
                daysOff:
                    properties:
                        id:
                           type: integer
                        unixStartDate:
                           type: integer
                        unixEndDate:
                           type: integer
                        deleted:
                           type: boolean
                        user:
                            type: object
                            properties:
                                id:
                                   type: integer
                    persistence:
                        driver: orm
                        model: App\Entity\DayOff
                        repository: App\Repository\DaysOffRepository
                        finder: ~
                        provider: ~
                holiday:
                    properties:
                        id:
                           type: integer
                        unixStartDate:
                           type: integer
                        unixEndDate:
                           type: integer
                        deleted:
                           type: boolean
                    persistence:
                        driver: orm
                        model: App\Entity\Holiday
                        repository: App\Repository\HolidayRepository
                        finder: ~
                        provider: ~
                presenceEdited:
                    properties:
                        id:
                           type: integer
                        unixStartDate:
                           type: integer
                        unixEndDate:
                           type: integer
                        unixOriginalStartDate:
                           type: integer
                        unixOriginalEndDate:
                           type: integer
                        user:
                            type: object
                            properties:
                                id:
                                   type: integer
                        deleted:
                           type: boolean
                    persistence:
                        driver: orm
                        model: App\Entity\PresenceEdited
                        repository: App\Repository\PresenceEditedRepository
                        finder: ~
                        provider: ~
                presence:
                    properties:
                        id:
                           type: integer
                        unixStartDate:
                           type: integer
                        unixEndDate:
                           type: integer
                        user:
                            type: object
                            properties:
                                id:
                                   type: integer
                        deleted:
                           type: boolean
                    persistence:
                        driver: orm
                        model: App\Entity\Presence
                        repository: App\Repository\PresenceRepository
                        finder: ~
                        provider: ~
