fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        lis:
            client: default
            types:
                user:
                    properties:
                        id:
                            type: integer
                        firstName: ~
                        lastName: ~
                        email: ~
                        userType:
                            type: object
                            properties:
                                id: ~
                        position:
                            type: object
                            properties:
                                id: ~
                        team:
                            type: object
                            properties:
                                id: ~
                        deleted:
                            type: boolean
                    persistence:
                        driver: orm
                        model: App\Entity\User
                        repository: App\Repository\UserRepository
                        finder: ~
                        provider: ~
                project:
                    properties:
                        id:
                           type: integer
                        name:
                           type: string
                        description:
                           type: string
                        startDate:
                           type: date
                        estimatedDuration:
                           type: date
                        deleted:
                           type: boolean
                        projectType:
                            type: object
                            properties:
                                id:
                                   type: integer
                        userCreated:
                            type: object
                            properties:
                                id:
                                   type: integer
                    persistence:
                        driver: orm
                        model: App\Entity\Project
                        repository: App\Repository\ProjectRepository
                        finder: ~
                        provider: ~


