fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        lis:
            client: default
            types:
                user:
                    properties:
                        id:
                            type: integer
                        firstName:
                            type: string
                        lastName:
                            type: string
                        email:
                            type: string
                        deleted:
                            type: boolean
                        userType:
                            type: object
                            properties:
                                id:
                                    type: integer
                        position:
                            type: object
                            properties:
                                id:
                                    type: integer
                        team:
                            type: object
                            properties:
                                id:
                                    type: integer
                    persistence:
                        driver: orm
                        model: App\Entity\User
                        repository: App\Repository\UserRepository
                        finder: ~
                        provider: ~
                project:
                    properties:
                        id:
                           type: integer
                        name:
                           type: string
                        description:
                           type: string
                        startDate:
                           type: date
                        estimatedDuration:
                           type: date
                        deleted:
                           type: boolean
                        finished:
                           type: boolean
                        projectType:
                            type: object
                            properties:
                                id:
                                   type: integer
                        userCreated:
                            type: object
                            properties:
                                id:
                                   type: integer
                    persistence:
                        driver: orm
                        model: App\Entity\Project
                        repository: App\Repository\ProjectRepository
                        finder: ~
                        provider: ~
                participant:
                    properties:
                        id:
                            type: integer
                        project:
                            type: object
                            properties:
                                id:
                                   type: integer
                    persistence:
                        driver: orm
                        model: App\Entity\Participant
                        repository: App\Repository\ParticipantRepository
                        finder: ~
                        provider: ~
