#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"


user_current:
    path: /api/user/current
    controller: App\Controller\UserController::getCurrentUserAction

user_edit:
    path: /api/user/edit
    controller: App\Controller\UserController::editUserAction