#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

#User

user_current:
    path: /api/user/current
    controller: App\Controller\UserController::getCurrentUserAction

user_edit:
    path: /api/user/edit
    controller: App\Controller\UserController::editUserAction

create_user_data:
    path: /api/user/create-data
    controller: App\Controller\UserController::getCreateUserDataAction

create_user_create:
    path: /api/user/create
    controller: App\Controller\UserController::createUserAction

get_users:
    path: /api/users/get
    controller: App\Controller\UserController::getUsersAction

search_users:
    path: /api/user/search
    controller: App\Controller\UserController::getSearchUserAction


#Presence

presence_checkIn:
    path: /api/presence/checkin
    controller: App\Controller\PresenceController::checkInAction

presence_checkOut:
    path: /api/presence/checkout
    controller: App\Controller\PresenceController::checkOutAction

presence_userIsCheckedIn:
    path: /api/presence/userIsCheckedIn
    controller: App\Controller\PresenceController::userIsCheckedInAction