#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

#User

user_current:
    path: /api/user/current
    controller: App\Controller\UserController::getCurrentUserAction

user_edit:
    path: /api/user/edit
    controller: App\Controller\UserController::editUserAction

user_data:
    path: /api/user/data
    controller: App\Controller\UserController::getUserDataAction

create_user:
    path: /api/user/create
    controller: App\Controller\UserController::createUserAction

get_users:
    path: /api/users/get
    controller: App\Controller\UserController::getUsersAction

search_users:
    path: /api/user/search
    controller: App\Controller\UserController::getSearchUserAction

get_user_by_id:
    path: /api/user/get
    controller: App\Controller\UserController::getUserByIdAction

update_users:
    path: /api/user/update
    controller: App\Controller\UserController::getUpdateUserAction

delete_users:
    path: /api/user/delete
    controller: App\Controller\UserController::getDeleteUserAction

lis_getAllUsers:
    path: /api/getAllUsers
    controller: App\Controller\UserController::getAllUsersAction

#Presence

presence_getPresenceByUser:
    path: /api/getPresenceByUser
    controller: App\Controller\PresenceController::getPresenceByUserAction

presence_getEditedPresences:
    path: /api/getEditedPresences
    controller: App\Controller\PresenceController::getEditedPresencesAction

presence_editPresence:
    path: /api/editPresence
    controller: App\Controller\PresenceController::editPresenceAction

presence_checkIn:
    path: /api/presence/checkin
    controller: App\Controller\PresenceController::checkInAction

presence_checkOut:
    path: /api/presence/checkout
    controller: App\Controller\PresenceController::checkOutAction

presence_userIsCheckedIn:
    path: /api/presence/userIsCheckedIn
    controller: App\Controller\PresenceController::userIsCheckedInAction

presence_filterEditedPresences:
    path: /api/filterEditedPresences
    controller: App\Controller\PresenceController::filterEditedPresencesAction

presence_filterPresences:
    path: /api/filterPresences
    controller: App\Controller\PresenceController::filterPresencesAction


#Project

lis_newproject:
   path: /api/np
   controller: App\Controller\ProjectController:newProjectAction

lis_getProjectById:
   path: /api/getProjectById
   controller: App\Controller\ProjectController:getProjectByIdAction

lis_searchProjects:
   path: /api/searchProjects
   controller: App\Controller\ProjectController:searchProjectsAction

lis_finishProject:
   path: /api/finishProject
   controller: App\Controller\ProjectController:finishProjectAction

lis_filterProjects:
   path: /api/filterProjects
   controller: App\Controller\ProjectController:filterProjectsAction

lis_getproject:
   path: /api/gp
   controller: App\Controller\ProjectController:getProjectAction

lis_getprojectPP:
   path: /api/gppp
   controller: App\Controller\ProjectController:getProjectPPAction

lis_editproject:
   path: /api/ep
   controller: App\Controller\ProjectController:editProjectAction

lis_deleteproject:
   path: /api/dp
   controller: App\Controller\ProjectController:deleteProjectAction

lis_etapeProject:
   path: /api/dtp
   controller: App\Controller\EtapeController:newEtapeProjectAction

lis_taskProject:
   path: /api/tp
   controller: App\Controller\TaskController:taskProjectAction

#Etape

lis_getEtape:
   path: /api/ge
   controller: App\Controller\EtapeController:getEtapesAction

lis_getEtapeByProject:
   path: /api/getEtapeByProject
   controller: App\Controller\EtapeController:getEtapeByProjectAction

lis_editEtape:
   path: /api/editEtape
   controller: App\Controller\EtapeController:editEtapeAction

lis_getEtapeById:
   path: /api/getEtapeById
   controller: App\Controller\EtapeController:getEtapeByIdAction

lis_getEtapeHours:
   path: /api/getEtapeHours
   controller: App\Controller\EtapeController:getEtapeHoursAction

#Task

lis_getTaskForParticipant:
   path: /api/getTaskForParticipant
   controller: App\Controller\TaskController:getTaskForParticipantAction

lis_getTask:
   path: /api/gett
   controller: App\Controller\TaskController:getTaskAction

lis_doneTask:
   path: /api/donet
   controller: App\Controller\TaskController:doneTaskAction

lis_getTaskById:
   path: /api/getTaskById
   controller: App\Controller\TaskController:getTaskByIdAction

lis_getTaskByEtape:
   path: /api/getTaskByEtape
   controller: App\Controller\TaskController:getTaskByEtapeAction

lis_editTask:
   path: /api/editTask
   controller: App\Controller\TaskController:editTaskAction

lis_removeTask:
   path: /api/removeTask
   controller: App\Controller\TaskController:removeTaskAction

#Participant

lis_getParticipants:
   path: /api/getParticipants
   controller: App\Controller\ParticipantController:getParticipantAction

lis_getProjectsForParticipant:
   path: /api/getProjectsForParticipant
   controller: App\Controller\ParticipantController:getProjectsForParticipantAction

lis_getParticipantForTask:
   path: /api/getParticipantForTask
   controller: App\Controller\ParticipantController:getParticipantForTaskAction

lis_getNoneParticipants:
   path: /api/getNoneParticipants
   controller: App\Controller\ParticipantController:getNoneParticipantAction

lis_addParticipant:
   path: /api/addParticipant
   controller: App\Controller\ParticipantController:addParticipantAction

lis_removeParticipant:
   path: /api/removeParticipant
   controller: App\Controller\ParticipantController:removeParticipantAction

lis_getParticipantForProject:
   path: /api/getParticipantForProject
   controller: App\Controller\ParticipantController:getParticipantForProjectAction

lis_getParticipantTypes:
   path: /api/getParticipantTypes
   controller: App\Controller\ParticipantController:getParticipantTypesAction


#Report

lis_getInitialInfo:
   path: /api/getInitialInfo
   controller: App\Controller\ReportController:getInitialInfoAction

lis_getInfoForMonth:
   path: /api/getInfoForMonth
   controller: App\Controller\ReportController:getInfoForMonthAction

#Team

lis_newTeam:
  path: /api/newTeam
  controller: App\Controller\TeamController:newTeamAction

lis_getTeams:
  path: /api/getTeams
  controller: App\Controller\TeamController:getTeamsAction

lis_removeTeam:
  path: /api/removeTeam
  controller: App\Controller\TeamController:removeTeamAction

lis_getTeamById:
  path: /api/getTeamById
  controller: App\Controller\TeamController:getTeamByIdAction

lis_editTeam:
  path: /api/editTeam
  controller: App\Controller\TeamController:editTeamAction

lis_getUsersForTeam:
  path: /api/getUsersForTeam
  controller: App\Controller\TeamController:getUsersForTeamAction

lis_removeFromTeam:
  path: /api/removeFromTeam
  controller: App\Controller\TeamController:removeFromTeamAction


#Salary

lis_newSalary:
  path: /api/newSalary
  controller: App\Controller\SalaryController:newSalaryAction

lis_filterSalary:
  path: /api/filterSalary
  controller: App\Controller\SalaryController:filterSalaryAction

lis_getSalaries:
  path: /api/getSalaries
  controller: App\Controller\SalaryController:getSalariesAction

lis_removeSalary:
  path: /api/removeSalary
  controller: App\Controller\SalaryController:removeSalaryAction

lis_getSalaryById:
  path: /api/getSalaryById
  controller: App\Controller\SalaryController:getSalaryByIdAction

lis_editSalary:
  path: /api/editSalary
  controller: App\Controller\SalaryController:editSalaryAction

#Business Client

lis_newBusinessClient:
  path: /api/newBusinessClient
  controller: App\Controller\BusinessClientController:newBusinessClientAction

lis_getBusinessClients:
  path: /api/getBusinessClients
  controller: App\Controller\BusinessClientController:getBusinessClientsAction

lis_getBusinessClientById:
  path: /api/getBusinessClientById
  controller: App\Controller\BusinessClientController:getBusinessClientByIdAction

lis_editBusinessClient:
  path: /api/editBusinessClient
  controller: App\Controller\BusinessClientController:editBusinessClientAction

lis_getCountries:
  path: /api/getCountries
  controller: App\Controller\BusinessClientController:getCountriesAction

#Bonus

lis_newBonus:
  path: /api/newBonus
  controller: App\Controller\BonusController:newBonusAction

lis_filterBonuses:
  path: /api/filterBonuses
  controller: App\Controller\BonusController:filterBonusesAction

lis_getBonuses:
  path: /api/getBonuses
  controller: App\Controller\BonusController:getBonusesAction

lis_removeBonus:
  path: /api/removeBonus
  controller: App\Controller\BonusController:removeBonusAction

lis_getBonusById:
  path: /api/getBonusById
  controller: App\Controller\BonusController:getBonusByIdAction

lis_editBonus:
  path: /api/editBonus
  controller: App\Controller\BonusController:editBonusAction

#Days Off

lis_getDaysOffStats:
  path: /api/getDaysOffStats
  controller: App\Controller\DaysOffController:getDaysOffStatsAction

lis_getDaysOffStatsByUser:
  path: /api/getDaysOffStatsByUser
  controller: App\Controller\DaysOffController:getDaysOffStatsByUserAction

lis_newDaysOff:
  path: /api/newDaysOff
  controller: App\Controller\DaysOffController:newDaysOffAction

lis_getDaysOff:
  path: /api/getDaysOff
  controller: App\Controller\DaysOffController:getDaysOffAction

lis_getDaysOffUser:
  path: /api/getDaysOffUser
  controller: App\Controller\DaysOffController:getDaysOffUserAction

lis_removeDaysOff:
  path: /api/removeDaysOff
  controller: App\Controller\DaysOffController:removeDaysOffAction

lis_editDaysOff:
  path: /api/editDaysOff
  controller: App\Controller\DaysOffController:editDaysOffAction

lis_getDayOffById:
  path: /api/getDayOffById
  controller: App\Controller\DaysOffController:getDayOffByIdAction

lis_decisionDaysOff:
  path: /api/decideDaysOff
  controller: App\Controller\DaysOffController:decisionDaysOffAction

lis_filterDaysOff:
  path: /api/filterDaysOff
  controller: App\Controller\DaysOffController:filterDaysOffAction

#Project Type

lis_newProjectType:
  path: /api/newProjectType
  controller: App\Controller\ProjectTypeController:newProjectTypeAction

lis_getProjectTypes:
  path: /api/getProjectTypes
  controller: App\Controller\ProjectTypeController:getProjectTypesAction

lis_removeProjectType:
  path: /api/removeProjectType
  controller: App\Controller\ProjectTypeController:removeProjectTypeAction

#Participant Type

lis_newParticipantType:
  path: /api/newParticipantType
  controller: App\Controller\ParticipantTypeController:newParticipantTypeAction

lis_removeParticipantType:
  path: /api/removeParticipantType
  controller: App\Controller\ParticipantTypeController:removeParticipantTypeAction

lis_getAllParticipantTypes:
  path: /api/getAllParticipantTypes
  controller: App\Controller\ParticipantTypeController:getAllParticipantTypesAction

#User Type

lis_newUserType:
  path: /api/newUserType
  controller: App\Controller\UserTypeController:newUserTypeAction

lis_getUserTypes:
  path: /api/getUserTypes
  controller: App\Controller\UserTypeController:getUserTypesAction

lis_removeUserTypes:
  path: /api/removeUserTypes
  controller: App\Controller\UserTypeController:removeUserTypesAction

#Position

lis_newPosition:
  path: /api/newPosition
  controller: App\Controller\PositionController:newPositionAction

lis_getPositions:
  path: /api/getPositions
  controller: App\Controller\PositionController:getPositionsAction

lis_removePosition:
  path: /api/removePosition
  controller: App\Controller\PositionController:removePositionAction

lis_decideDaysOff:
  path: /api/decideDaysOff
  controller: App\Controller\PositionController:decideDaysOffAction

#Holiday

lis_newHoliday:
  path: /api/newHoliday
  controller: App\Controller\HolidayController:newHolidayAction

lis_getHolidays:
  path: /api/getHolidays
  controller: App\Controller\HolidayController:getHolidaysAction

lis_removeHoliday:
  path: /api/removeHoliday
  controller: App\Controller\HolidayController:removeHolidayAction

lis_filterHolidays:
  path: /api/filterHolidays
  controller: App\Controller\HolidayController:filterHolidaysAction