#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"
fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

#User

user_current:
    path: /api/user/current
    controller: App\Controller\UserController::getCurrentUserAction

user_edit:
    path: /api/user/edit
    controller: App\Controller\UserController::editUserAction

user_data:
    path: /api/user/data
    controller: App\Controller\UserController::getUserDataAction

create_user:
    path: /api/user/create
    controller: App\Controller\UserController::createUserAction

get_users:
    path: /api/users/get
    controller: App\Controller\UserController::getUsersAction

search_users:
    path: /api/user/search
    controller: App\Controller\UserController::getSearchUserAction

get_user_by_id:
    path: /api/user/get
    controller: App\Controller\UserController::getUserByIdAction

update_users:
    path: /api/user/update
    controller: App\Controller\UserController::getUpdateUserAction

delete_users:
    path: /api/user/delete
    controller: App\Controller\UserController::getDeleteUserAction


#Presence

presence_checkIn:
    path: /api/presence/checkin
    controller: App\Controller\PresenceController::checkInAction

presence_checkOut:
    path: /api/presence/checkout
    controller: App\Controller\PresenceController::checkOutAction

presence_userIsCheckedIn:
    path: /api/presence/userIsCheckedIn
    controller: App\Controller\PresenceController::userIsCheckedInAction


#Project

lis_newproject:
   path: /api/np
   controller: App\Controller\ProjectController:newProjectAction

lis_searchProjects:
   path: /api/searchProjects
   controller: App\Controller\ProjectController:searchProjectsAction

lis_finishProject:
   path: /api/finishProject
   controller: App\Controller\ProjectController:finishProjectAction

lis_filterProjects:
   path: /api/filterProjects
   controller: App\Controller\ProjectController:filterProjectsAction

lis_getproject:
   path: /api/gp
   controller: App\Controller\ProjectController:getProjectAction

lis_getprojectPP:
   path: /api/gppp
   controller: App\Controller\ProjectController:getProjectPPAction

lis_editproject:
   path: /api/ep
   controller: App\Controller\ProjectController:editProjectAction

lis_deleteproject:
   path: /api/dp
   controller: App\Controller\ProjectController:deleteProjectAction

lis_etapeProject:
   path: /api/dtp
   controller: App\Controller\EtapeController:newEtapeProjectAction

lis_taskProject:
   path: /api/tp
   controller: App\Controller\TaskController:taskProjectAction

#Etape
lis_getEtape:
   path: /api/ge
   controller: App\Controller\EtapeController:getEtapesAction

lis_editEtape:
   path: /api/editEtape
   controller: App\Controller\EtapeController:editEtapeAction

lis_getEtapeById:
   path: /api/getEtapeById
   controller: App\Controller\EtapeController:getEtapeByIdAction

lis_getEtapeHours:
   path: /api/getEtapeHours
   controller: App\Controller\EtapeController:getEtapeHoursAction

#Task
lis_getTask:
   path: /api/gett
   controller: App\Controller\TaskController:getTaskAction

lis_doneTask:
   path: /api/donet
   controller: App\Controller\TaskController:doneTaskAction

lis_getTaskById:
   path: /api/getTaskById
   controller: App\Controller\TaskController:getTaskByIdAction

lis_editTask:
   path: /api/editTask
   controller: App\Controller\TaskController:editTaskAction

#Participant

lis_getParticipants:
   path: /api/getParticipants
   controller: App\Controller\ParticipantController:getParticipantAction

lis_getParticipantForTask:
   path: /api/getParticipantForTask
   controller: App\Controller\ParticipantController:getParticipantForTaskAction

lis_getNoneParticipants:
   path: /api/getNoneParticipants
   controller: App\Controller\ParticipantController:getNoneParticipantAction

lis_addParticipant:
   path: /api/addParticipant
   controller: App\Controller\ParticipantController:addParticipantAction

lis_removeParticipant:
   path: /api/removeParticipant
   controller: App\Controller\ParticipantController:removeParticipantAction

lis_getParticipantForProject:
   path: /api/getParticipantForProject
   controller: App\Controller\ParticipantController:getParticipantForProjectAction

lis_getParticipantTypes:
   path: /api/getParticipantTypes
   controller: App\Controller\ParticipantController:getParticipantTypesAction


#Report

lis_getInitialInfo:
   path: /api/getInitialInfo
   controller: App\Controller\ReportController:getInitialInfoAction

lis_getInfoForMonth:
   path: /api/getInfoForMonth
   controller: App\Controller\ReportController:getInfoForMonthAction