# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    mailer_user: 'a'
    mailer_password: 'a'
    allowed_origins: '*'


services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    OAuth2\OAuth2: '@fos_oauth_server.server'
    FOS\OAuthServerBundle\Propel\AccessTokenManager: '@fos_oauth_server.access_token_manager.default'
    FOS\ElasticaBundle\Finder\PaginatedFinderInterface: '@fos_elastica.finder.lis.user'
    FOS\ElasticaBundle\Finder\PaginatedFinderInterface: '@fos_elastica.finder.lis.project'
    FOS\ElasticaBundle\Finder\PaginatedFinderInterface: '@fos_elastica.finder.lis.participant'
    FOS\ElasticaBundle\Finder\PaginatedFinderInterface: '@fos_elastica.finder.lis.bonus'
    FOS\ElasticaBundle\Finder\PaginatedFinderInterface: '@fos_elastica.finder.lis.salary'
    FOS\ElasticaBundle\Finder\PaginatedFinderInterface: '@fos_elastica.finder.lis.dayOff'
    FOS\ElasticaBundle\Finder\PaginatedFinderInterface: '@fos_elastica.finder.lis.holiday'
    FOS\ElasticaBundle\Finder\PaginatedFinderInterface: '@fos_elastica.finder.lis.presenceEdited'
    FOS\ElasticaBundle\Finder\PaginatedFinderInterface: '@fos_elastica.finder.lis.presence'

    app.api.factory:
        class: App\API\Factory\ApiFactory
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@logger"]


    app.cors.listener:
        class: App\EventListener\CorsListener
        tags:
             - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest , priority: 100}
             - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -100}

    app.token.authenticator:
        class: App\Security\TokenAuthenticator
        arguments: ['@fos_oauth_server.server', "@doctrine.orm.entity_manager"]

    app.file.service:
        class: App\Service\FileService

    app.user.type:
        class: App\Service\UserTypeService
        arguments: ["@doctrine.orm.entity_manager"]

    app.user:
        class: App\Service\UserService
        arguments: ["@doctrine.orm.entity_manager"]

    app.position:
        class: App\Service\PositionService
        arguments: ["@doctrine.orm.entity_manager"]

    app.team:
        class: App\Service\TeamService
        arguments: ["@doctrine.orm.entity_manager"]

    app.get.users:
        class: App\Service\GetUsers
        arguments: ["@doctrine.orm.entity_manager"]

    app.project:
         class: App\Service\ProjectService
         arguments: ["@doctrine.orm.entity_manager"]
    app.task:
         class: App\Service\TaskService
         arguments: ["@doctrine.orm.entity_manager"]
    app.etape:
         class: App\Service\EtapeService
         arguments: ["@doctrine.orm.entity_manager"]
    app.country:
         class: App\Service\CountryService
         arguments: ["@doctrine.orm.entity_manager"]