App\Entity\Account:
    type: entity
    table: account
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        accountNumber:
            type: string
            lenght: 255
            nullable: false
        type:
            type: string
            length: 255
            nullable: false
        deleted:
            type: boolean
            nullable: false
    manyToOne:
         bank:
            targetEntity: Bank
            joinColumn:
                name: bank_id
                referencedColumnName: id
