App\Entity\Bank:
    type: entity
    table: bank
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            lenght: 255
            nullable: false
        swift:
            type: string
            length: 255
            nullable: true
        deleted:
            type: boolean
            nullable: false