App\Entity\City:
    type: entity
    table: city
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            lenght: 255
            nullable: true
        zipCode:
            type: string
            lenght: 255
            nullable: true
    manyToOne:
         country:
            targetEntity: Country
            joinColumn:
                name: country_id
                referencedColumnName: id