App\Entity\DayOff:
    type: entity
    table: day_off

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        start:
            type: datetime
            nullable: false
        end:
            type: datetime
            nullable: true
        workdays:
            type: integer
            nullable: false
        dateCreated:
            type: datetime
            nullable: false
        dateUpdated:
            type: datetime
            nullable: false
        status:
            type: string
            nullable: false
        reasonDeclined:
            type: text
            nullable: true
        deleted:
            type: boolean
            nullable: false
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id

