App\Entity\Participant:
    type: entity
    table: participant

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        deleted:
            type: boolean
            nullable: true
    manyToOne:
        participantType:
            targetEntity: ParticipantType
            joinColumn:
                name: participant_type_id
                referencedColumnName: id
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
        project:
            targetEntity: Project
            joinColumn:
                name: project_id
                referencedColumnName: id