App\Entity\PresenceEdited:
    type: entity
    table: presence_edited

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        start:
            type: datetime
            nullable: true
        end:
            type: datetime
            nullable: true
        originalStart:
            type: datetime
            nullable: true
        originalEnd:
            type: datetime
            nullable: true
        dateCreated:
            type: datetime
            nullable: false
        dateUpdated:
            type: datetime
            nullable: true
        deleted:
            type: boolean
            nullable: true
    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
        presence:
            targetEntity: Presence
            joinColumn:
                name: presence_id
                referencedColumnName: id