App\Entity\Presence:
    type: entity
    table: presence

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        start:
            type: datetime
            nullable: false
        end:
            type: datetime
            nullable: true
        closed:
            type: boolean
            nullable: false
            default: false
        businessCheckOut:
            type: boolean
            nullable: true
            default: false
        dateCreated:
            type: datetime
            nullable: false
        dateUpdated:
            type: datetime
            nullable: true
        deleted:
            type: boolean
            nullable: true
        year:
            type: integer
            nullable: true
        month:
            type: integer
            nullable: true
        eightHours:
            type: boolean
            nullable: false
        autoClosed:
            type: boolean
            nullable: false

    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id