App\Entity\ProjectExpense:
    type: entity
    table: project_expense

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        amount:
            type: decimal
            nullable: false
        description:
            type: text
            lenght: 255
            nullable: true
        dateCreated:
            type: datetime
            nullable: false
        dateUpdated:
            type: datetime
            nullable: false
        deleted:
            type: boolean
            nullable: false
    manyToOne:
        project:
            targetEntity: Project
            joinColumn:
                name: project_id
                referencedColumnName: id
        currency:
            targetEntity: Currency
            joinColumn:
                name: currency_id
                referencedColumnName: id