App\Entity\RefreshToken:
    type: entity
    table: refreshtoken
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        client:
            targetEntity: Client
            joinColumn:
                name: client_id
                referencedColumnName: id
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id