App\Entity\Salary:
    type: entity
    table: salary

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        bruto:
            type: decimal
            nullable: false
        neto:
            type: decimal
            nullable: false
        dateValid:
            type: datetime
            nullable: true
        dateCreated:
            type: datetime
            nullable: false
        dateUpdated:
            type: datetime
            nullable: false
        deleted:
            type: boolean
            nullable: false

    manyToOne:
        user:
            targetEntity: User
            joinColumn:
                name: user_id
                referencedColumnName: id
