App\Entity\Task:
    type: entity
    table: task

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            lenght: 255
            nullable: true
        description:
            type: text
            nullable: true
        dateCreated:
            type: datetime
            nullable: false
        dateUpdated:
            type: datetime
            nullable: false
        deleted:
            type: boolean
            nullable: false
        hour:
            type: integer
            nullable: false
        start:
            type: datetime
            nullable: false
        end:
            type: datetime
            nullable: false
    manyToOne:
        participent:
            targetEntity: Participant
            joinColumn:
                name: participant_id
                referencedColumnName: id
        etape:
            targetEntity: Etape
            joinColumn:
                name: etape_id
                referencedColumnName: id