App\Entity\User:
    type: entity
    table: user

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        firstName:
            type: string
            lenght: 255
            nullable: true
        lastName:
            type: string
            lenght: 255
            nullable: true
